import { useEffect, useRef, useState } from 'react';
import type { LearningState } from '../../state/learningState';
import type { Module3RevisedScreen } from '../../data/module3/module3RevisedScreens';
import { jiruAmbaCase } from '../../data/module3/jiruAmbaCaseNarrative';
import { normalizeSafetyState, normalizeStableIds } from './module3Batch2State';
import './module3-batch2.css';

type ChangeState = (updater: (prev: LearningState) => LearningState) => void;
type Complete = (value?: Record<string, unknown>) => void;

const practiceKey = (screenId: string) => `module3_revised_${screenId.toLowerCase().replace(/[^a-z0-9]+/g, '_')}`;
const recordFor = (state: LearningState, screenId: string) => {
  const value = state.practiceCheckState[practiceKey(screenId)];
  return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
};
const caseSectionIds = ['case-section.setting','case-section.plan','case-section.process','case-section.actors'] as const;
const questionIds = ['design-question.context-differences','design-question.standards-responsibilities','design-question.rights-holders-barriers','design-question.actors-responsibility-influence','design-question.causes-capacity','design-question.inclusion-accountability-risk-design'] as const;

function useScreenReplay(screenId: string, onChangeState: ChangeState) {
  useEffect(() => {
    const handleReplay = (event: Event) => {
      const replayedScreenId = (event as CustomEvent<{ screenId?: string }>).detail?.screenId;
      if (replayedScreenId !== screenId) return;
      onChangeState((prev) => {
        const practiceCheckState = { ...prev.practiceCheckState };
        delete practiceCheckState[practiceKey(screenId)];
        return {
          ...prev,
          practiceCheckState,
          screenProgress: {
            ...prev.screenProgress,
            module_03_project_design: (prev.screenProgress.module_03_project_design || []).filter((id) => id !== screenId),
          },
        };
      });
    };
    window.addEventListener('course:replay-screen', handleReplay);
    return () => window.removeEventListener('course:replay-screen', handleReplay);
  }, [onChangeState, screenId]);
}

const designQuestions = [
  { id: questionIds[0], title: 'Context and differences', question: 'What is happening, and who may experience it differently?', examine: ['service, livelihood, information, and participation conditions','differences between town, rural, and remote settings','groups that may experience the proposed plan differently','possible inequality patterns','assumptions that need verification'], known: 'Jiru Amba includes a small town and surrounding rural kebeles. Distance, access to information, disability, gender, livelihood, income, and local influence may affect people differently.', unknown: ['which groups face the highest-priority barriers','how common each possible barrier is','which assumptions are supported by evidence','which design changes are required'], outputs: ['Context and Inequality Scan'], feedback: 'This question area prepares the first practical analysis. The learner should identify facts, possible patterns, assumptions, and evidence needs without treating every concern as confirmed.' },
  { id: questionIds[1], title: 'Standards and responsibilities', question: 'Which rights, standards, commitments, and responsibilities are relevant?', examine: ['human rights principles','relevant policies and service standards','public responsibilities','project commitments','standards for access, participation, information, quality, dignity, and accountability'], known: 'The draft concerns public services, livelihood opportunities, consultation, and feedback. Public and service actors have roles connected to these areas.', unknown: ['which references are most relevant to each issue','which actor holds which specific responsibility','whether the draft reflects the selected standards','what gaps require design changes'], outputs: ['Policy and Standards Map'], feedback: 'This question area helps connect local project choices to standards and responsibilities. It should not become only a list of legal instruments.' },
  { id: questionIds[2], title: 'Rights-holders and barriers', question: 'Which specific groups are connected to the issue, and what may limit access or influence?', examine: ['specific rights-holder groups','information and communication barriers','physical and accessibility barriers','distance and transport','time and care responsibilities','social, institutional, or economic barriers','barriers to participation, influence, benefit, feedback, and follow-up'], known: 'The plan refers to women, young people, persons with disabilities, market users, low-income households, and residents of rural kebeles.', unknown: ['which barrier applies to which group','the relative importance of each barrier','whether barriers interact','which design implication should follow'], outputs: ['Rights-Holder and Barrier Map'], feedback: 'Broad categories do not provide enough analysis. Later practice will connect specific groups, barriers, and design implications.' },
  { id: questionIds[3], title: 'Actors, responsibility, and influence', question: 'Who has responsibility, who provides support, and who influences decisions?', examine: ['primary duty-bearers','service and sector actors','supporting actors','community and representative actors','realistic CSO roles','formal authority','practical influence','gatekeeping, relationships, and access to decision spaces'], known: 'The case includes woreda actors, kebele-level actors, service staff, committees, local leaders, community representatives, informal intermediaries, Awra, and Selam.', unknown: ['the final actor classification','the level of each actor’s influence','which actor controls information or access','which role is appropriate for Awra','where responsibility and influence do not match'], outputs: ['Duty-Bearer and Actor Responsibility Map','Power and Influence Map'], feedback: 'Formal responsibility and practical influence are related but different. The later tools examine both without assuming that the CSO should replace public responsibility.' },
  { id: questionIds[4], title: 'Causes and capacity', question: 'Why may the issue continue, and what may limit an effective response?', examine: ['visible problems','immediate causes','underlying barriers','deeper structural or normative factors','rights-holder capacity','duty-bearer mandate, knowledge, skills, resources, coordination, incentives, willingness, and accountability'], known: 'The design contains proposed activities, but detailed responsibilities, accessibility measures, response arrangements, and implementation conditions have not been fully agreed.', unknown: ['the main root cause','which gap is a capacity gap','whether a gap concerns mandate, resources, coordination, incentives, willingness, or another factor','which response is realistic'], outputs: ['Root-Cause and Capacity-Gap Map'], feedback: 'An implementation gap should not automatically be explained as unwillingness or lack of training. Later analysis distinguishes causes and capacity dimensions.' },
  { id: questionIds[5], title: 'Inclusion, accountability, risk, and design change', question: 'How should people participate, receive a response, remain protected, and influence the final design?', examine: ['gender and disability design implications','accessibility and reasonable accommodation','meaningful participation','influence over decisions','information and feedback channels','responsible review and response','explanation and follow-up','risk and do-no-harm','evidence and monitoring','changes required in the objective, activities, logic, indicators, and implementation arrangements'], known: 'The draft proposes consultation meetings and feedback boxes, but participation methods, accessibility, response arrangements, risk measures, and monitoring questions are not fully agreed.', unknown: ['whether participation is meaningful','whether the proposed channels are accessible or safe','who receives and responds to feedback','which risks require mitigation','the final design repair'], outputs: ['Gender and Disability Design Check','Participation and Accountability Pathway','Risk and Do-No-Harm Board','HRBA Project Design Repair Package'], feedback: 'Meetings and feedback boxes alone do not demonstrate meaningful participation or accountability. Later tools examine influence, response, accessibility, risk, and design change.' },
] as const;

function StageNav({ stage, unlocked, onSelect, labels }: { stage: number; unlocked: number; onSelect: (stage: number) => void; labels: string[] }) {
  return <nav className="m3-b2-stage-nav" aria-label="Screen stages">{labels.map((label,index) => { const number=index+1; const locked=number>unlocked; return <button key={label} type="button" aria-current={stage===number?'step':undefined} disabled={locked} aria-describedby={locked?`m3-b2-stage-${number}-reason`:undefined} className={stage===number?'is-active':number<unlocked?'is-complete':''} onClick={()=>onSelect(number)}><span>{number<unlocked?'✓':number}</span><b>{label}</b>{locked&&<small id={`m3-b2-stage-${number}-reason`}>{number===2?'Complete the previous review first.':'Review all required items first.'}</small>}</button>; })}</nav>;
}

export function Module3Screen3({ screen,state,onChangeState,onComplete }: { screen: Module3RevisedScreen; state: LearningState; onChangeState: ChangeState; onComplete: Complete }) {
  useScreenReplay(screen.id, onChangeState);
  const saved=recordFor(state,screen.id);
  const [reviewedSections,setReviewedSections]=useState(()=>normalizeStableIds(saved.caseSectionsReviewed,caseSectionIds,caseSectionIds));
  const [reviewedQuestions,setReviewedQuestions]=useState(()=>normalizeStableIds(saved.questionAreasReviewed,questionIds,questionIds));
  const [stage,setStage]=useState(Math.min(3,Math.max(1,Number(saved.stage)||1)));
  const [openSection,setOpenSection]=useState<string|null>(null);
  const [activeQuestion,setActiveQuestion]=useState<number|null>(null);
  const [answer,setAnswer]=useState(String(saved.selectedAnswer||''));
  const [feedback,setFeedback]=useState(saved.checkComplete===true?'Correct. The same case continues across the module. Each tool examines one part of the design, and the outputs are carried forward into later decisions and the final snapshot.':'');
  const [checkComplete,setCheckComplete]=useState(saved.checkComplete===true);
  const [assetOk,setAssetOk]=useState(true);
  const detailRef=useRef<HTMLHeadingElement>(null); const cardRefs=useRef<Array<HTMLButtonElement|null>>([]); const originRef=useRef(0);
  const sectionsComplete=reviewedSections.length===4, questionsComplete=reviewedQuestions.length===6, complete=sectionsComplete&&questionsComplete&&checkComplete;
  const unlocked=questionsComplete?3:sectionsComplete?2:1;
  const save=(patch:Record<string,unknown>)=>onChangeState(prev=>({...prev,practiceCheckState:{...prev.practiceCheckState,[practiceKey(screen.id)]:{...recordFor(prev,screen.id),interactionProgressVersion:1,...patch}}}));
  useEffect(()=>{ save({caseSectionsReviewed:reviewedSections,questionAreasReviewed:reviewedQuestions,selectedAnswer:answer,checkComplete,screen3Complete:complete,stage:Math.min(stage,unlocked)}); },[reviewedSections,reviewedQuestions,answer,checkComplete,complete]); // eslint-disable-line react-hooks/exhaustive-deps
  const openCase=(id:string)=>{setOpenSection(current=>current===id?null:id); if(!reviewedSections.includes(id))setReviewedSections([...reviewedSections,id]);};
  const openQuestion=(index:number)=>{originRef.current=index; const id=designQuestions[index].id; if(!reviewedQuestions.includes(id))setReviewedQuestions([...reviewedQuestions,id]); setActiveQuestion(index); requestAnimationFrame(()=>detailRef.current?.focus({preventScroll:true}));};
  const backToGrid=()=>{setActiveQuestion(null); requestAnimationFrame(()=>cardRefs.current[originRef.current]?.focus({preventScroll:true}));};
  useEffect(()=>{if(activeQuestion===null)return; const handler=(event:KeyboardEvent)=>{if(event.key==='Escape')backToGrid();}; window.addEventListener('keydown',handler); return()=>window.removeEventListener('keydown',handler);});
  const check=()=>{const messages:Record<string,string>={A:'This is not correct. The draft includes potentially useful activities, but the design still needs analysis and improvement. The case is not presented as a model to copy.',B:'This is not correct. Jiru Amba is fictional. Learners should not enter identifiable complaints, people, institutions, or locations.',C:'Correct. The same case continues across the module. Each tool examines one part of the design, and the outputs are carried forward into later decisions and the final snapshot.',D:'This is not correct. Jiru Amba remains the continuous practice case from context analysis through project-design repair and final review.'};setFeedback(messages[answer]);setCheckComplete(answer==='C');};
  const sectionContent=[
    <><p>Jiru Amba includes a small town and several surrounding rural kebeles.</p><p>People in the area use:</p><ul>{jiruAmbaCase.setting.slice(2).map(item=><li key={item.id}>{item.label};</li>)}</ul><p>People do not all experience these services, opportunities, and decision-making processes in the same way.</p><p>Distance, transport, income, language, literacy, disability access, care responsibilities, access to information, social relationships, and local influence may affect how different people receive information, reach services, participate, express priorities, influence decisions, benefit, provide feedback, and receive a response.</p><p>These are matters for analysis. The case does not assume that every group faces the same barrier or that one explanation applies to every part of Jiru Amba.</p></>,
    <><p>The woreda is preparing a draft Inclusive Local Development and Service Improvement Plan. In this course, the draft is referred to as the Jiru Amba Futures Plan.</p><p>The plan aims to improve selected public services and livelihood opportunities and to involve community members in planning and feedback.</p><ol>{jiruAmbaCase.planAreas.map(item=><li key={item.id}><strong>{item.label}</strong><p>{item.description}</p></li>)}</ol><p>The proposed activities may respond to important local priorities. Before the plan is finalized, the project team still needs to examine whether the priorities, methods, responsibilities, participation arrangements, expected results, and monitoring approach are adequately rights-based, inclusive, accountable, realistic, and risk-aware.</p></>,
    <><p>The following information forms part of the fictional case.</p><ul>{jiruAmbaCase.processFacts.map(item=><li key={item.id}>{item.label}</li>)}</ul><p>The final design has not yet been approved. These facts do not provide the complete analysis.</p><p>They give the project team a starting point for asking: What is already known? What is assumed? What needs to be verified? Whose experience may not yet be visible? What should change before implementation?</p></>,
    <><p>The case includes rights-holders, public duty-bearers, service actors, community actors, and supporting organizations. Their exact responsibilities, influence, interests, capacities, and relationships will be examined later.</p><h3>Rights-holder groups represented in the case</h3><ul>{jiruAmbaCase.rightsHolders.map(item=><li key={item.id}>{item.label}{item.description?` — ${item.description}`:''}</li>)}</ul><p>These categories should not be treated as uniform groups.</p><h3>Public and service actors represented in the case</h3><ul>{jiruAmbaCase.actors.slice(0,7).map(item=><li key={item.id}>{item.label}</li>)}</ul><p>The course will not assume that every gap results from unwillingness or only from lack of capacity.</p><h3>Community and other actors represented in the case</h3><ul>{jiruAmbaCase.actors.slice(7,13).map(item=><li key={item.id}>{item.label}</li>)}</ul><p>These actors should not automatically be treated as representative, inclusive, appropriate, or safe for every issue.</p><h3>Awra and Selam</h3><p>Awra is the fictional local CSO supporting the learning case. The woreda has asked Awra to support consultation and help review the draft design before it is finalized.</p><p>Selam, an Awra programme officer, will follow the case through the module. Awra may support accessible information, participation, evidence and analysis, dialogue, coordination, capacity development, referral and follow-up, monitoring of agreed commitments, and improvement of its own accountability. Awra should not automatically take over the permanent responsibilities of public institutions or service actors.</p></>,
  ];
  const sectionTitles=['The local setting','The Inclusive Local Development and Service Improvement Plan','The planning process to date','People and actors connected to the plan'];
  return <main className="m3-screen m3-b2-screen" aria-labelledby={`${screen.id}-title`}><article className="m3-b2-canvas"><header className="m3-b2-header"><p className="m3-context-label">{screen.eyebrow}</p><h1 id={`${screen.id}-title`}>{screen.title}</h1><p>Review the fictional project case that you will analyze and improve throughout Module 3.</p></header><section className="m3-b2-hero"><div><h2>A fictional practice case</h2><p>Jiru Amba is a fictional Ethiopian local development setting created for this course.</p><p>The case does not describe a real woreda, kebele, organization, official, community member, complaint, or project. It provides a common and safe practice setting so that all learners can examine the same project-design information.</p><p>Throughout Module 3, you will return to this case. Each practical screen will focus on a different part of the design and will produce an output that contributes to the final HRBA Project Design Improvement Snapshot.</p></div>{assetOk?<img src="/assets/hrba/modules/module-3/case/m3-s03-case-overview-jiru-amba.webp" alt="Fictional Jiru Amba setting with a small town, rural kebeles, market, water point, health post, and diverse local actors reviewing a draft development plan." onError={()=>setAssetOk(false)}/>:<div className="m3-b2-image-fallback" role="img" aria-label="Jiru Amba case illustration unavailable">Case illustration</div>}</section><StageNav stage={stage} unlocked={unlocked} onSelect={setStage} labels={['Review the case','Examine the design questions','Check your understanding']}/>
  {stage===1&&<section className="m3-b2-stage"><h2>Review the case</h2><p>Review the Jiru Amba setting, the proposed plan, the planning process to date, and the people and actors connected to it.</p><p className="m3-b2-progress" aria-live="polite">{reviewedSections.length} of 4 case sections reviewed</p><div className="m3-b2-accordions">{caseSectionIds.map((id,index)=>{const open=openSection===id,reviewed=reviewedSections.includes(id);return <section key={id}><button type="button" aria-expanded={open} aria-controls={`${id}-panel`} onClick={()=>openCase(id)}><span>{index+1}</span><b>{sectionTitles[index]}</b><em>{open?'Currently open':reviewed?'✓ Reviewed':'Not reviewed'}</em><i aria-hidden="true">⌄</i></button>{open&&<div id={`${id}-panel`} className="m3-b2-accordion-panel">{sectionContent[index]}</div>}</section>;})}</div><div className="m3-b2-support-grid"><article><h3>One case, examined step by step</h3><p>You will use the same Jiru Amba case across the practical screens. Each later screen will use a limited part of the case and will add information needed for that task. The outputs should remain connected.</p></article><article><h3>Use the information provided; identify what needs verification</h3><p>Do not invent missing facts or assume that a possible concern has already been confirmed. Identify the question, state assumptions carefully, and identify information that should be verified safely.</p></article><article><h3>Prepare to examine the case</h3><p>Before finalizing activities, the team needs to examine context, rights-holders, responsibilities, barriers, influence, participation, accountability, risks, evidence, and expected change.</p></article></div>{sectionsComplete&&<button className="m3-primary-button" type="button" onClick={()=>setStage(2)}>Continue to design questions</button>}</section>}
  {stage===2&&<section className="m3-b2-stage"><h2>What should the project team examine?</h2><p>Review the six question areas. Each one will be examined through a practical tool later in the module.</p><p className="m3-b2-progress" aria-live="polite">{reviewedQuestions.length} of 6 design-question areas reviewed</p>{activeQuestion===null?<div className="m3-b2-question-grid">{designQuestions.map((item,index)=><button ref={node=>{cardRefs.current[index]=node;}} key={item.id} type="button" className={reviewedQuestions.includes(item.id)?'is-reviewed':''} onClick={()=>openQuestion(index)} aria-label={`Question area ${index+1} of 6: ${item.title}`}><span>{index+1}</span><em>{reviewedQuestions.includes(item.id)?'✓ Reviewed':'Open'}</em><b>{item.title}</b><p>{item.question}</p><strong>Open question area →</strong></button>)}</div>:(()=>{const item=designQuestions[activeQuestion];return <article className="m3-b2-question-detail"><p className="m3-context-label">QUESTION AREA {activeQuestion+1} OF 6</p><h2 ref={detailRef} tabIndex={-1}>{item.title}</h2><p className="m3-b2-question-lead">{item.question}</p><div className="m3-b2-detail-columns"><section><h3>What the team needs to examine</h3><ul>{item.examine.map(value=><li key={value}>{value}</li>)}</ul></section><section><h3>What the case already tells us</h3><p>{item.known}</p><h3>What is not yet known</h3><ul>{item.unknown.map(value=><li key={value}>{value}</li>)}</ul></section></div><section className="m3-b2-later-output"><h3>{item.outputs.length>1?'Later outputs':'Later output'}</h3><ul>{item.outputs.map(value=><li key={value}>{value}</li>)}</ul><p><strong>Reviewed:</strong> {item.feedback}</p></section><div className="m3-b2-actions"><button type="button" className="m3-secondary-button" onClick={()=>openQuestion((activeQuestion+5)%6)}>Previous question</button><button type="button" className="m3-primary-button" onClick={()=>openQuestion((activeQuestion+1)%6)}>Next question</button><button type="button" className="m3-secondary-button" onClick={backToGrid}>Back to question areas</button></div></article>;})()}{questionsComplete&&activeQuestion===null&&<button className="m3-primary-button" type="button" onClick={()=>setStage(3)}>Continue to understanding check</button>}</section>}
  {stage===3&&<section className="m3-b2-stage m3-b2-check"><h2>Check your understanding</h2><fieldset><legend>Select the statement that best explains how the Jiru Amba case will be used in Module 3.</legend>{[['A','Jiru Amba is a complete model project that learners should copy without further analysis.'],['B','Jiru Amba is a real district case used to document identifiable service concerns and complaints.'],['C','Jiru Amba is a continuous fictional practice case. Learners will examine it step by step and use each analysis output to improve the project design.'],['D','Jiru Amba is used only for the Context and Inequality Scan and is then replaced by a different case.']].map(([id,text])=><label className="m3-check-option" key={id}><input type="radio" name="m3-b2-s3-check" value={id} checked={answer===id} disabled={checkComplete} onChange={()=>{setAnswer(id);setFeedback('');}}/><span><strong>{id}.</strong> {text}</span></label>)}</fieldset><button type="button" className="m3-primary-button" disabled={!answer||checkComplete} onClick={check}>Check answer</button>{feedback&&<div className={`m3-b2-feedback ${checkComplete?'is-correct':''}`} aria-live="polite">{feedback}</div>}</section>}
  <footer className="m3-b2-footer"><p>{complete?'All case sections and question areas reviewed; understanding check complete.':'Complete the current stage to continue.'}</p><button type="button" className="m3-primary-button" disabled={!complete} onClick={()=>onComplete()}>{screen.continueLabel}</button></footer></article></main>;
}

const phaseIds=['snapshot-phase.understand-issue','snapshot-phase.actors-causes','snapshot-phase.inclusion-accountability-safety','snapshot-phase.improve-prepare'] as const;
const outputExists=(state:LearningState,screenId:string,keys:readonly string[])=>{const record=recordFor(state,screenId); return keys.some(key=>record[key]!=null&&(typeof record[key]!=='object'||Object.keys(record[key] as object).length>0));};
const phases=[
  {id:phaseIds[0],title:'Understand the issue',purpose:'This phase establishes the design issue and the people, standards, responsibilities, and barriers connected to it.',outputs:[['Context and inequality findings','Screen 5','M3-R05',['contextInequalityScan']],['Rights, standards, policies, and responsibilities','Screen 6','M3-R06',['policyStandardsMap','generatedMapRows']],['Rights-holders and barriers','Screen 7','M3-R07',['submittedOutput','generatedMapRows']]],carry:'These findings establish the issue, the people connected to it, relevant standards and responsibilities, and the barriers that later actor and cause analysis must address.',confirmation:'Phase 1 prepares the factual and standards-based foundation for the rest of the design process.'},
  {id:phaseIds[1],title:'Understand actors and causes',purpose:'This phase examines who has responsibility, who provides support, who influences decisions, and what may limit change.',outputs:[['Duty-bearers, supporting actors, and realistic CSO roles','Screen 8','M3-R08',['generatedResponsibilityRows','responsibilityMap']],['Power and influence','Screen 9','M3-R09',['generatedActorRows','powerMapSummary']],['Root causes and capacity gaps','Screen 10','M3-R10',['rootCauseCapacityGapMap','rootCauseSummary']]],carry:'These findings clarify responsibility, influence, causes, and response gaps before participation, accountability, risk, and activities are designed.',confirmation:'Phase 2 helps prevent the project from assigning responsibilities or activities without understanding who can act, who influences decisions, and what limits change.'},
  {id:phaseIds[2],title:'Strengthen inclusion, participation, accountability, and safety',purpose:'This phase checks whether the way the project will operate is inclusive, accessible, accountable, and risk-aware.',outputs:[['Gender and disability design implications','Screen 11','M3-R11',['markerLiteDashboard','portfolioSummary']],['Participation and accountability arrangements','Screen 12','M3-R12',['participationAccountabilityPathway']],['Risk and do-no-harm measures','Screen 13','M3-R13',['riskDoNoHarmBoard','portfolioSummary']]],carry:'These outputs define how the project should operate and what requirements the repaired design must address.',confirmation:'Phase 3 checks whether the design supports inclusion, influence, response, accessibility, risk management, and safe implementation.'},
  {id:phaseIds[3],title:'Improve the design and prepare for implementation',purpose:'This phase uses the earlier analysis to improve the draft project and prepare it for further review.',outputs:[['Repaired project design','Screen 14','M3-R14',['designRepairPackage','repairedObjective']],['Draft-plan review findings','Screen 15','M3-R17',['draftPlanReviewPreview','appliedCheckReview','draftPlanReviewNote']],['Applied knowledge and final snapshot review','Screens 16–17','M3-R20',['appliedKnowledgeCheck','screen20']],['Implementation watch-points','Screen 17 and Module 4','M3-R21',['module3PortfolioSnapshot','m3ProjectDesignImprovementSnapshot']]],carry:'These outputs bring the earlier reasoning into one draft design product and identify what requires attention during implementation.',confirmation:'Phase 4 does not simply summarize earlier work. It uses the analysis to repair the project and prepare it for review and implementation.'},
] as const;

const safetyItems=[
  ['safe-item.01','Some residents of remote kebeles may receive planning information later than residents near the town.','safe','Correct. This is a generalized possible pattern. It does not name a person, household, exact location, or complaint.','This can be used in the course because it is broad and non-identifying. It should still be treated as an assumption requiring verification unless the fictional case confirms it.'],
  ['safe-item.02','A named woman from a named kebele reported that a named official refused to respond to her complaint.','do-not-write','Correct. This identifies a complainant, location, official, and complaint. It may create confidentiality, safeguarding, protection, relationship, and data-security risks.','This should not be entered. Identifiable complaints belong only in appropriate organizational complaint or case-management procedures.'],
  ['safe-item.03','People with mobility limitations may need an accessible meeting location and transport arrangements.','safe','Correct. This is a generalized design consideration and does not disclose personal disability information.','This is safe as a broad accessibility consideration. Do not add names, diagnoses, personal histories, or identifying details.'],
  ['safe-item.04','A staff member uploaded a photograph of a child receiving services, together with the child’s name and village.','do-not-write','Correct. The image and details identify a child and a service context. This information must not be entered in the course.','This is not safe. Information about children requires strict safeguarding and data-protection procedures and should not be uploaded here.'],
  ['safe-item.05','The project team should verify whether the weekday meeting time limits participation for people with care or livelihood responsibilities.','safe','Correct. This is a non-identifying design question and clearly indicates that the issue still requires verification.','This is appropriate course input because it is framed as a generalized question, not as an accusation or confirmed fact.'],
  ['safe-item.06','A real survivor’s account is copied into the course to show why a referral pathway is needed.','do-not-write','Correct. Survivor stories must not be entered for learning purposes. Referral and safeguarding design can be discussed through fictional or generalized examples.','This should not be entered. A real survivor’s account may expose identity, safety, dignity, consent, and confidentiality concerns.'],
  ['safe-item.07','The draft does not yet identify who will receive feedback, how a response will be decided, or how people will learn what happened.','safe','Correct. This is a generalized project-design gap and does not identify a real complainant or actor.','This can be entered because it describes a design issue without disclosing sensitive or identifying information.'],
  ['safe-item.08','A project note combines a person’s job role, disability, small village, and meeting date, but does not include the person’s name.','do-not-write','Correct. A combination of indirect details may identify a person even when the name is omitted.','Removing the name is not always enough. Several details together may make a person identifiable.'],
] as const;

export function Module3Screen4({screen,state,onChangeState,onComplete}:{screen:Module3RevisedScreen;state:LearningState;onChangeState:ChangeState;onComplete:Complete}){
  useScreenReplay(screen.id, onChangeState);
  const saved=recordFor(state,screen.id); const normalizedSafety=normalizeSafetyState(saved,safetyItems.map(item=>item[0]));
  const [reviewed,setReviewed]=useState(()=>normalizeStableIds(saved.snapshotPhasesReviewed,phaseIds,phaseIds)); const [openPhase,setOpenPhase]=useState<string|null>(null); const [stage,setStage]=useState(Math.min(3,Math.max(1,Number(saved.stage)||1))); const [activeItem,setActiveItem]=useState(Math.min(7,Math.max(0,Number(saved.activeSafetyItem)||0))); const [answers,setAnswers]=useState<Record<string,string>>(()=>normalizedSafety.answers); const [checked,setChecked]=useState<Record<string,boolean>>(()=>normalizedSafety.checked); const [ack,setAck]=useState(saved.safeUseAcknowledged===true); const [assetOk,setAssetOk]=useState(true);
  const correctIds=safetyItems.filter(item=>checked[item[0]]&&answers[item[0]]===item[2]).map(item=>item[0]); const phasesComplete=reviewed.length===4,safetyComplete=correctIds.length===8,complete=phasesComplete&&safetyComplete&&ack; const unlocked=safetyComplete?3:phasesComplete?2:1;
  const save=(patch:Record<string,unknown>)=>onChangeState(prev=>({...prev,practiceCheckState:{...prev.practiceCheckState,[practiceKey(screen.id)]:{...recordFor(prev,screen.id),interactionProgressVersion:1,...patch}}}));
  useEffect(()=>{save({batch2ItemSetVersion:8,snapshotPhasesReviewed:reviewed,safetyAnswers:answers,safetyChecked:checked,safetyComplete,safeUseAcknowledged:ack,screen4Complete:complete,activeSafetyItem:activeItem,stage:Math.min(stage,unlocked)});},[reviewed,answers,checked,safetyComplete,ack,complete,activeItem]); // eslint-disable-line react-hooks/exhaustive-deps
  const togglePhase=(id:string)=>{setOpenPhase(current=>current===id?null:id);if(!reviewed.includes(id))setReviewed([...reviewed,id]);}; const item=safetyItems[activeItem]; const itemCorrect=checked[item[0]]&&answers[item[0]]===item[2];
  return <main className="m3-screen m3-b2-screen" aria-labelledby={`${screen.id}-title`}><article className="m3-b2-canvas"><header className="m3-b2-header"><p className="m3-context-label">{screen.eyebrow}</p><h1 id={`${screen.id}-title`}>{screen.title}</h1><p>Each practical screen will add one part to a cumulative draft project-design output.</p></header><section className="m3-b2-hero"><div><h2>One cumulative project-design output</h2><p>Module 3 does not end with a collection of separate quiz answers.</p><p>Each practical screen produces a small analysis or design output. These outputs are brought together in your HRBA Project Design Improvement Snapshot.</p><p>The snapshot will show what you identified, what still requires verification, how one analysis informed the next, what should change in the project design, and what needs attention during implementation.</p><p>At this point, the snapshot is not yet complete. Its sections will be filled as you work through the module.</p></div>{assetOk?<img src="/assets/hrba/modules/module-3/snapshot/m3-s04-snapshot-overview-empty.webp" alt="Empty four-phase HRBA project-design snapshot showing planned sections for analysis, actors and causes, inclusive and safe design, and preparation for implementation." onError={()=>setAssetOk(false)}/>:<div className="m3-b2-image-fallback" role="img" aria-label="Snapshot illustration unavailable">Snapshot illustration</div>}</section><StageNav stage={stage} unlocked={unlocked} onSelect={setStage} labels={['Explore the snapshot','Practise safe course input','Confirm the safe-use rule']}/>
  {stage===1&&<section className="m3-b2-stage"><h2>How your snapshot will develop</h2><p>Open each phase to see which outputs it will contain and how those outputs will be used later.</p><p className="m3-b2-progress" aria-live="polite">{reviewed.length} of 4 snapshot phases reviewed</p><div className="m3-b2-phase-path">{phases.map((phase,index)=>{const open=openPhase===phase.id,phaseReviewed=reviewed.includes(phase.id),completed=phase.outputs.filter(output=>outputExists(state,output[2],output[3])).length;return <section key={phase.id}><button type="button" aria-expanded={open} aria-controls={`${phase.id}-panel`} onClick={()=>togglePhase(phase.id)}><span>{index+1}</span><b>{phase.title}</b><em>{phaseReviewed?'Phase reviewed':'Phase not reviewed'}</em><small>{phase.outputs.length} planned output sections · {completed} later outputs completed</small><i aria-hidden="true">⌄</i></button>{open&&<div id={`${phase.id}-panel`} className="m3-b2-phase-panel"><p>{phase.purpose}</p><ul>{phase.outputs.map(output=>{const done=outputExists(state,output[2],output[3]);return <li key={output[0]}><div><strong>{output[0]}</strong><span>Produced on: {output[1]}</span></div><em>{done?'Later output completed':'Not started'}</em></li>})}</ul><p className="m3-b2-carry"><strong>Carry forward:</strong> {phase.carry}</p><p><strong>Phase reviewed:</strong> {phase.confirmation}</p></div>}</section>})}</div><div className="m3-b2-support-grid"><article><h3>How the snapshot may be used</h3><p>The snapshot may support learning, discussion with colleagues, further project development, preparation for implementation, technical review questions, Module 4 learning, and future facilitated collaborative review.</p></article><article><h3>A draft learning and project-design product</h3><p>It does not confirm every assumption, replace field verification, provide legal or safeguarding approval, replace technical, management, financial or organizational approval, or authorize sensitive-information collection or sharing.</p></article></div>{phasesComplete&&<button className="m3-primary-button" type="button" onClick={()=>setStage(2)}>Continue to safe course input</button>}</section>}
  {stage===2&&<section className="m3-b2-stage"><h2>What is safe to enter in the course?</h2><p>Classify each example as Safe to write in the course or Do not write in the course.</p><div className="m3-b2-safety-defs"><p><strong>Safe to write in the course:</strong> Fictional, generalized, or non-identifying information that is sufficient for the learning task.</p><p><strong>Do not write in the course:</strong> Information that identifies or may identify a person, complaint, survivor, location, organization, official, child, or confidential case.</p></div><p className="m3-b2-progress" aria-live="polite">{correctIds.length} of 8 examples classified correctly</p><article className="m3-b2-safety-item"><p className="m3-context-label">EXAMPLE {activeItem+1} OF 8</p><fieldset><legend>{item[1]}</legend>{[['safe','Safe to write in the course'],['do-not-write','Do not write in the course']].map(([value,label])=><label className="m3-check-option" key={value}><input type="radio" name={`m3-b2-${item[0]}`} value={value} checked={answers[item[0]]===value} onChange={()=>{setAnswers({...answers,[item[0]]:value});setChecked({...checked,[item[0]]:false});}}/><span>{label}</span></label>)}</fieldset><button type="button" className="m3-primary-button" disabled={!answers[item[0]]} onClick={()=>setChecked({...checked,[item[0]]:true})}>Check answer</button>{checked[item[0]]&&<div className={`m3-b2-feedback ${itemCorrect?'is-correct':''}`} aria-live="polite">{itemCorrect?item[3]:item[4]}</div>}<div className="m3-b2-actions"><button type="button" className="m3-secondary-button" disabled={activeItem===0} onClick={()=>setActiveItem(activeItem-1)}>Previous example</button><button type="button" className="m3-primary-button" disabled={activeItem===7} onClick={()=>setActiveItem(activeItem+1)}>Next example</button></div></article><div className="m3-b2-support-grid"><article><h3>Use fictional, generalized, and non-identifying information</h3><p>Use Jiru Amba first. Where a later screen allows an own-context example, enter only the minimum generalized information needed to practise.</p></article><article><h3>Sensitive evidence requires appropriate organizational procedures</h3><p>The course platform is not a case-management, complaint-management, safeguarding, or confidential evidence system.</p></article></div>{safetyComplete&&<button className="m3-primary-button" type="button" onClick={()=>setStage(3)}>Continue to safe-use rule</button>}</section>}
  {stage===3&&<section className="m3-b2-stage m3-b2-ack"><h2>Before you begin the practical tools</h2><blockquote><strong>Dawit:</strong> Use Jiru Amba as the practice case first. When a later screen offers an own-context field, use only a generalized, non-identifying example. Sensitive evidence belongs in the appropriate systems and procedures established by your organization, not in this course.</blockquote><label><input type="checkbox" checked={ack} aria-describedby="m3-b2-ack-note" onChange={event=>setAck(event.target.checked)}/><span>I understand that course entries should remain fictional, generalized, or non-identifying.</span></label><p id="m3-b2-ack-note">This acknowledgement does not authorize the collection or use of sensitive real-world information.</p><article><h3>Your first snapshot section</h3><p>Your first practical output will be the Context and Inequality Scan.</p><p>It will help you examine what is happening in Jiru Amba; which groups may experience the situation differently; which barriers may exist; which assumptions should be checked; and what information can be verified safely.</p><p>When that output is complete, it will become the first section of your HRBA Project Design Improvement Snapshot.</p></article></section>}
  <footer className="m3-b2-footer"><p>{complete?'Snapshot orientation and safe-use preparation complete.':'Complete the current stage to continue.'}</p><button type="button" className="m3-primary-button" disabled={!complete} onClick={()=>onComplete()}>{screen.continueLabel}</button></footer></article></main>;
}
